deepseek:

  api-key: sk-111f8a7b9ab54c63b3c12132b6afb5b1
  url: https://api.deepseek.com/chat/completions
  model: deepseek-chat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homet?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

serve:
server:
  port: 8080
  address: 0.0.0.0